package com.gelox.backend.entities;

public enum TipoEvento {
    DESPACHO,
    CIERRE_CAJA,
    ALERTA_STOCK,
    NUEVO_REGISTRO,
    EDICION_USUARIO,
    DESHABILITAR_USUARIO,
    HABILITAR_USUARIO,
    INICIO_SESION,
    CIERRE_SESION,
    ACTUALIZACION_PERFIL,
    CAMBIO_CONTRASENA,
    CREAR_PRODUCTO,
    EDITAR_PRODUCTO,
    DESACTIVAR_PRODUCTO,
    ACTIVAR_PRODUCTO
}